set serveroutput on

exec dbms_output.put_line('Run this on the Primary');


SELECT LOCAL.THREAD#, LOCAL.SEQUENCE# FROM
 (SELECT THREAD#, SEQUENCE# FROM V$ARCHIVED_LOG WHERE DEST_ID=1)
 LOCAL WHERE
 LOCAL.SEQUENCE# NOT IN
 (SELECT SEQUENCE# FROM V$ARCHIVED_LOG WHERE DEST_ID=2 AND
 THREAD# = LOCAL.THREAD#);

